// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYTDKYaVo0opJYCoA7ebX2hvZ9B5-46w',
    appId: '1:933288094291:web:eac53537f0fef81c51f4a6',
    messagingSenderId: '933288094291',
    projectId: 'friendapp-746de',
    authDomain: 'friendapp-746de.firebaseapp.com',
    storageBucket: 'friendapp-746de.appspot.com',
    measurementId: 'G-NN98DP1CNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ48a6jLrkf5W_HgcVToDdZ4bCT3TonEI',
    appId: '1:933288094291:android:bfc42555eac8353d51f4a6',
    messagingSenderId: '933288094291',
    projectId: 'friendapp-746de',
    storageBucket: 'friendapp-746de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3uYk_QJMGQzxtQ1VtA7r7MH6QqY_izjo',
    appId: '1:933288094291:ios:1b36bc915e83873a51f4a6',
    messagingSenderId: '933288094291',
    projectId: 'friendapp-746de',
    storageBucket: 'friendapp-746de.appspot.com',
    iosClientId: '933288094291-35vjommpsog3h8p6psf2ot5j8dhqpnk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3uYk_QJMGQzxtQ1VtA7r7MH6QqY_izjo',
    appId: '1:933288094291:ios:1b36bc915e83873a51f4a6',
    messagingSenderId: '933288094291',
    projectId: 'friendapp-746de',
    storageBucket: 'friendapp-746de.appspot.com',
    iosClientId: '933288094291-35vjommpsog3h8p6psf2ot5j8dhqpnk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendActivity',
  );
}
